@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}
@baseURL = http://{{host}}/api/blogs

@id = 64e0e1732983b1ec0dc6f6fe
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdhc3Ryb3BvZG8zIiwiaWQiOiI2NGUxNmRiNTc5YzUwZDFhNDgyOTkyNTQiLCJpYXQiOjE2OTI2NTU5MzN9.O99KUykwnXIgxV_NRtA6H30vdovRjVoO8HsyBx80QAo

### Get Blogs
GET {{baseURL}} HTTP/1.1
Authorization: Bearer {{token}}

### Get Blog by ID
GET {{baseURL}}/{{id}} HTTP/1.1
Authorization: Bearer {{token}}

### Add Blog
POST {{baseURL}} HTTP/1.1
Content-type: application/json
Authorization: Bearer {{token}}

{
    "title": "Test blog 2",
    "author": "Test",
    "url": "/test-blog",
    "likes": 0
}

### Delete Blog
DELETE {{baseURL}}/{{id}} HTTP/1.1
Authorization: Bearer {{token}}

### Post comment
POST {{baseURL}}/{{id}}/comments HTTP/1.1
Content-type: application/json
Authorization: Bearer {{token}}

{
    "text": "comment 3"
}
