@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@baseURL = http://{{host}}/api/persons

@id = 371966

### Get Persons
GET {{baseURL}} HTTP/1.1

### Get Person by ID
GET {{baseURL}}/{{id}} HTTP/1.1

### Delete Person
DELETE {{baseURL}}/{{id}}

### Add Person
POST {{baseURL}} HTTP/1.1
Content-type: application/json

{
    "name": "Felipe Areyuna",
    "number": "333333"
}