@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@baseURL = http://{{host}}/api/persons

@id = 64d953984102fdde506fc1b0

### Get Persons
GET {{baseURL}} HTTP/1.1

### Get Person by ID
GET {{baseURL}}/{{id}} HTTP/1.1

### Delete Person
DELETE {{baseURL}}/{{id}}

### Add Person
POST {{baseURL}} HTTP/1.1
Content-type: application/json

{
    "name": "",
    "number": "333333-23234"
}

### Update Person
PUT {{baseURL}}/{{id}} HTTP/1.1
Content-type: application/json

{
    "number": ""
}